/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BrowserChart: typeof import('./src/components/chart/BrowserChart.vue')['default']
    DateChart: typeof import('./src/components/chart/DateChart.vue')['default']
    Footer: typeof import('./src/components/common/Footer.vue')['default']
    Loading: typeof import('./src/components/common/Loading.vue')['default']
    Message: typeof import('./src/components/common/Message.vue')['default']
    MonthChart: typeof import('./src/components/chart/MonthChart.vue')['default']
    Navbar: typeof import('./src/components/common/Navbar.vue')['default']
    RoleChart: typeof import('./src/components/chart/RoleChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YearChart: typeof import('./src/components/chart/YearChart.vue')['default']
  }
}
